### ISSUE TITLE
getting java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by deeTEEcee** [palantir/gradle-consistent-versions#422]
## What happened?

Gradle version: 5.4.1

Added the new plugin to my project on the root as specified. My project has several plugins and multiple subprojects. Once I ran `./gradlew subproject:tasks` or any simple command, I run into this error: 

```
> Task :buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/5.4.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;
        at com.palantir.gradle.versions.FuzzyPatternResolver.exactMatches(FuzzyPatternResolver.java:39)
        at com.palantir.gradle.versions.ImmutableFuzzyPatternResolver.access$101(ImmutableFuzzyPatternResolver.java:31)
        at com.palantir.gradle.versions.ImmutableFuzzyPatternResolver$InitShim.exactMatches(ImmutableFuzzyPatternResolver.java:58)
        at com.palantir.gradle.versions.ImmutableFuzzyPatternResolver.<init>(ImmutableFuzzyPatternResolver.java:38)
        at com.palantir.gradle.versions.ImmutableFuzzyPatternResolver.<init>(ImmutableFuzzyPatternResolver.java:31)
        at com.palantir.gradle.versions.ImmutableFuzzyPatternResolver$Builder.build(ImmutableFuzzyPatternResolver.java:280)
        at com.palantir.gradle.versions.VersionsProps.loadFromFile(VersionsProps.java:82)
        at com.palantir.gradle.versions.VersionsPropsPlugin.loadVersionsProps(VersionsPropsPlugin.java:268)
        at com.palantir.gradle.versions.VersionsPropsPlugin.apply(VersionsPropsPlugin.java:79)
        at com.palantir.gradle.versions.VersionsPropsPlugin.apply(VersionsPropsPlugin.java:51)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:267)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
        at com.palantir.gradle.versions.VersionsPropsPlugin.lambda$applyToRootProject$8(VersionsPropsPlugin.java:110)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:41)
        at org.gradle.internal.Actions.with(Actions.java:246)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$2$1.run(BuildOperationCrossProjectConfigurator.java:79)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$2.run(BuildOperationCrossProjectConfigurator.java:76)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:200)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:186)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.runProjectConfigureAction(BuildOperationCrossProjectConfigurator.java:73)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.access$400(BuildOperationCrossProjectConfigurator.java:32)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$1.doRunProjectConfigure(BuildOperationCrossProjectConfigurator.java:67)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator$BlockConfigureBuildOperation.run(BuildOperationCrossProjectConfigurator.java:121)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.runBlockConfigureAction(BuildOperationCrossProjectConfigurator.java:64)
        at org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator.subprojects(BuildOperationCrossProjectConfigurator.java:49)
        at org.gradle.api.internal.project.DefaultProject.subprojects(DefaultProject.java:656)
        at com.palantir.gradle.versions.VersionsPropsPlugin.applyToRootProject(VersionsPropsPlugin.java:110)
        at com.palantir.gradle.versions.VersionsPropsPlugin.apply(VersionsPropsPlugin.java:62)
        at com.palantir.gradle.versions.VersionsPropsPlugin.apply(VersionsPropsPlugin.java:51)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:267)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
        at com.palantir.gradle.versions.ConsistentVersionsPlugin.apply(ConsistentVersionsPlugin.java:30)
        at com.palantir.gradle.versions.ConsistentVersionsPlugin.apply(ConsistentVersionsPlugin.java:23)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:267)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:133)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$3.run(DefaultPluginRequestApplicator.java:151)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:225)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:148)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:49)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:190)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:364)
...
```
## What did you want to happen?
Just for the command to pass so I didn't break anything.

**Comment by carterkozak** [comment]
Does your project explicitly specify build script dependency on an old version of guava? ImmutableSet.toImmutableSet was added in 21.0, and gradle-consistent-versions states a dependency on guava 23.6.1-jre.

**Comment by iamdanfox** [comment]
@deeTEEcee the `ImmutableSet.toImmutableSet` method is provided by guava 21.0, and I think we actually depend on guava 23.6.1-jre. Could you run `./gradlew buildEnvironment` to see what's going on?

**Comment by deeTEEcee** [comment]
I appreciate the quick response.

@carterkozak that's what i thought but can't i resolve that with something like this?
```
buildscript {
    dependencies {
        classpath("com.google.guava:guava:23.6-jre")
    }
}
```
Same issues after I have this on the root project. 

So if i run `./gradlew buildEnvironment` with the old working environment before i added the plugin, I have this.
```
+--- com.google.guava:guava:27.1-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.5.2
|    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    +--- com.google.j2objc:j2objc-annotations:1.1
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
\--- com.github.kt3k.coveralls:com.github.kt3k.coveralls.gradle.plugin:2.9.0
     \--- gradle.plugin.org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.9.0
          +--- org.codehaus.groovy.modules.http-builder:http-builder:0.7.1
          |    +--- org.apache.httpcomponents:httpclient:4.2.1 -> 4.3
          |    |    +--- org.apache.httpcomponents:httpcore:4.3
          |    |    +--- commons-logging:commons-logging:1.1.3
          |    |    \--- commons-codec:commons-codec:1.6
          |    +--- net.sf.json-lib:json-lib:2.3
          |    |    +--- commons-beanutils:commons-beanutils:1.8.0
          |    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.1.3
          |    |    +--- commons-collections:commons-collections:3.2.1
          |    |    +--- commons-lang:commons-lang:2.4
          |    |    +--- commons-logging:commons-logging:1.1.1 -> 1.1.3
          |    |    \--- net.sf.ezmorph:ezmorph:1.0.6
          |    |         \--- commons-lang:commons-lang:2.3 -> 2.4
          |    +--- net.sourceforge.nekohtml:nekohtml:1.9.16
          |    |    \--- xerces:xercesImpl:2.9.1
          |    \--- xml-resolver:xml-resolver:1.2
          +--- org.apache.httpcomponents:httpmime:4.3
          |    \--- org.apache.httpcomponents:httpclient:4.3 (*)
          \--- org.eclipse.jgit:org.eclipse.jgit:5.5.1.201910021850-r
               +--- com.jcraft:jsch:0.1.55
               +--- com.jcraft:jzlib:1.1.1
               +--- com.googlecode.javaewah:JavaEWAH:1.1.6
               +--- org.slf4j:slf4j-api:1.7.2
               +--- org.bouncycastle:bcpg-jdk15on:1.61
               |    \--- org.bouncycastle:bcprov-jdk15on:1.61
               +--- org.bouncycastle:bcprov-jdk15on:1.61
               \--- org.bouncycastle:bcpkix-jdk15on:1.61
                    \--- org.bouncycastle:bcprov-jdk15on:1.61
```

In one of my subprojects, I do have this show up but it looks updated and even if I update that plugin to a compatible guava version, that didn't solve the problem.  
```
+--- com.palantir.docker:com.palantir.docker.gradle.plugin:0.22.1
|    \--- gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.22.1
|         \--- com.google.guava:guava:18.0 -> 27.0.1-jre (*)
```

**Comment by deeTEEcee** [comment]
I finally understand the cause of the issue (https://github.com/gradle/gradle/issues/4741), and just trying to answer my own questions:
* How do I figure out what dependencies exist in `buildSrc`?
* Knowing these dependencies, how can I prevent them from leaking into my project?

**Detail:** We have some libraries in `buildSrc` that has a dependency using `com.google.guava:guava:27.1-android` and that's the library that does not have ImmutableSet. 

I can close this ticket now.

**Comment by iamdanfox** [comment]
Woah that's quite an issue. I think @CRogers found something where dependencies of SettingsPlugins leaked into the regular buildscript classpath too.

Wondering if we should just shade guava here to avoid this problem forever?

**Comment by carterkozak** [comment]
I think there's an argument to be made for shading all gradle plugin dependencies. Plugins will be much larger, but substantially safer as well.

**Comment by CRogers** [comment]
I tried to make `publish-shadow-jar` in our internal jar publishing repo to automatically shade all dependencies for this reason. But it had issues (mainly the gradle shadow plugin has terrible O(n^2) behaviour for renaming packages, so it's just too slow).

I'm in favour of shading gradle plugins' dependencies, or at least the problematic ones, especially for settings plugins, if the dependencies cannot be removed entirely.

**Comment by robert3005** [comment]
I thought the whole point of `plugins` block, i.e. 
```
plugins {
  id "<plugin>"
}
```
was that it gives you classpath isolation? It's mentioned in gradle docs https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations. Maybe we should encourage people to use that?

**Comment by CRogers** [comment]
The plugins block probably would work better for dependencies. The issue is changing all our existing excavator machinery to support it and it makes it much harder to find out which repo a particular plugin came from. I know @iamdanfox has opinions here too.

**Comment by robert3005** [comment]
I think the hard bit is the subproject section but I think at this point all our plugins deal with multiproject setup, i.e. https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl. Maybe we should chase the reminders down and move to the improved syntax? I know we originally had issues specifically because of multiproject builds but maybe it's not such a big issue anymore.
